-- MySQL Script generated by MySQL Workbench
-- Fri Oct 22 17:25:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`esporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`esporte` (
  `idEsporte` INT NOT NULL AUTO_INCREMENT,
  `esporte` TEXT(50) NOT NULL,
  UNIQUE INDEX `idEsporte_UNIQUE` (`idEsporte` ASC) VISIBLE,
  PRIMARY KEY (`idEsporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cadastroSocioEsporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cadastroSocioEsporte` (
  `idcadastroSocioEsporte` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `esporte_idEsporte` INT NOT NULL,
  PRIMARY KEY (`idcadastroSocioEsporte`),
  INDEX `fk_cadastroSocioEsporte_esporte1_idx` (`esporte_idEsporte` ASC) VISIBLE,
  CONSTRAINT `fk_cadastroSocioEsporte_esporte1`
    FOREIGN KEY (`esporte_idEsporte`)
    REFERENCES `mydb`.`esporte` (`idEsporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cadastrosocios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cadastrosocios` (
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `dataNasc` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `cadastroSocioEsporte_idcadastroSocioEsporte` INT NOT NULL,
  INDEX `fk_cadastrosocios_cadastroSocioEsporte_idx` (`cadastroSocioEsporte_idcadastroSocioEsporte` ASC) VISIBLE,
  CONSTRAINT `fk_cadastrosocios_cadastroSocioEsporte`
    FOREIGN KEY (`cadastroSocioEsporte_idcadastroSocioEsporte`)
    REFERENCES `mydb`.`cadastroSocioEsporte` (`idcadastroSocioEsporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
